/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_learning_ndk_cmake_JNICMake */

#ifndef _Included_com_jack_learning_ndk_cmake_JNICMake
#define _Included_com_jack_learning_ndk_cmake_JNICMake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jack_learning_ndk_cmake_JNICMake
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_learning_ndk_cmake_JNICMake_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
