/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_jack_learning_ndk_cmake_JNICMake.h"
#include <string>
/* Header for class com_jack_learning_ndk_cmake_JNICMake */

extern "C"
JNIEXPORT jstring JNICALL
Java_com_jack_learning_ndk_cmake_JNICMake_test
  (JNIEnv *env, jclass classz){
    std::string hello = "call libjni-cmake.so success.";
    return env->NewStringUTF(hello.c_str());
}

