/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jack_learning_ndk_mk_JNIMK */

#ifndef _Included_com_jack_learning_ndk_mk_JNIMK
#define _Included_com_jack_learning_ndk_mk_JNIMK
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_jack_learning_ndk_mk_JNIMK
 * Method:    test
 * Signature: Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_learning_ndk_mk_JNIMK_test
        (JNIEnv *, jclass);

/*
 * Class:     com_jack_learning_ndk_mk_JNIMK
 * Method:    getStringFromJNI
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jack_learning_ndk_mk_JNIMK_getStringFromJNI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
